version: "3.9"

services:
  pytorch-server:
    build:
      args:
        - username=${USERN}
        - uidr=${UID}
        - gidr=${GID}
        - rtpass=${ROOTPASS}
      context: ../
      dockerfile: docker/Dockerfile
    image: pytorch_jupyter:v1
    container_name: pytorch-jupyter
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            count: all
            capabilities: [gpu]
    ports:
      - "8888:8888"
    volumes:
      - ../bin:/workspace/bin
      - ../data:/workspace/data
      - ../doc:/workspace/doc
      - ../notebooks:/workspace/notebooks
      - ../results:/workspace/results
      - ../src:/workspace/src
    init: true
    stdin_open: true
    tty: true
